name: Help
version: 0.3.1
main: me.taylorkelly.help.Help
authors: [jascotty2, tkelly]
commands:
  help:
    description: Your friendly /help menu
    usage: /<command> - Displays help for all commands